version: '3.8'

services:
  streamlit:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "${STREAMLIT_PORT}:8501"
    volumes:
      - ./app:/app
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          cpus: '${CPU_LIMIT}'
        reservations:
          cpus: '${CPU_RESERVATION}'
    restart: unless-stopped
